project:
  type: default
  output-dir: outputs

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    toc-location: left
    embed-resources: true
    code-fold: true
    code-tools: true
    fig-width: 8
    fig-height: 5
    fig-dpi: 300
    number-sections: true
    anchor-sections: true
    smooth-scroll: true
    citations-hover: true
    footnotes-hover: true
    
  pdf:
    pdf-engine: lualatex
    toc: true
    toc-depth: 3
    number-sections: true
    fig-width: 7
    fig-height: 4.5
    fig-dpi: 300
    fig-format: png
    keep-tex: false
    documentclass: report
    papersize: a4
    margin-left: 1in
    margin-right: 1in
    margin-top: 1in
    margin-bottom: 1in
    include-in-header:
      text: |
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}

execute:
  echo: false
  warning: false
  message: false
  freeze: auto
  cache: false
  
jupyter: python3

